### ISSUE TITLE
Accès protected au lieu de private dans la classe LabelRenderer

### ISSUE THREAD

**Issue by NetAssoPro** [ekyna/GlsUniBox#1]
Déjà un grand merci pour ce travail qui m'a beaucoup aidé pour intégrer l'interface avec GLS qui n'est pas ultra intuitive.
Tout semble fonctionner à merveille.
Je souhaitais juste overider un peu la class LabelRenderer cependant tout est en privée. Est il possible à l'avenir de passer certains éléments au moins en protected afin de pouvoir appliquer quelques léger changement. : $layout,$fonts, initialize().

**Comment by ekyna** [comment]
Bonjour @NetAssoPro 
N'hésitez pas à soumettre un **Pull Request** pour appliquer les changement voulu.
